### ISSUE TITLE
No device /dev/stderr exists

### ISSUE THREAD

**Issue by vladonemo** [spryker/docker-sdk#181]
### Which release, branch or hash of Docker SDK are you using?
master branch

### Which operating system (platform/version/architecture) are you using?
Azure Pipelines ubuntu-18.04 VMImage

### What is the issue that you're experiencing?
docker/sdk can't be executed. Failing with:
`./docker/sdk: line 60: /dev/stderr: No such device or address`

#### What are the steps to reproduce the issue?
Just run for instance `docker/sdk boot deploy.yml` as an Azure Pipeline task

#### What is the expected result of these steps in the absence of the issue?
The `docker/sdk` runs with no error

#### What is the actual result?
Build fails

### What possible solutions and/or workarounds for the issue do you see?
Replace `>/dev/stderr` with `>&2` in all bash scripts

**Comment by marek-obuchowicz** [comment]
:+1: that would also unblock us - this problem happens on our setup as well, Debian 10/Jenkins

**Comment by sprymiker** [comment]
Thanks for the finding. The PR is reviewed. Given to QA.
