### ISSUE TITLE
testing.env file only generated for projects with Yves Frontend

### ISSUE THREAD

**Issue by jabrandes** [spryker/docker-sdk#218]
### Which release, branch or hash of Docker SDK are you using?
3608ed559d53d14df39e740c37b46b761633fefe

### Which operating system (platform/version/architecture) are you using?
macOS Big Sur 11.4

### What is the issue that you're experiencing?
The `testing.env` file required for testing is only built when an Yves-Application is configured for a project. This hinders the use of Spryker in projects relying purely on Glue as an interface to custom frontend implementations.

#### What are the steps to reproduce the issue?
1. Clone the B2B Demoshop (https://github.com/spryker-shop/b2b-demo-shop.git)
2. Remove the Yves Application Definitions from `deploy.dev.yml` file (keys `groups/*/applications/yves_*`)
3. Remove the Yves-Related Pyz-Modules (`src/Pyz/Yves` directory) and Module Tests (`tests/PyzTest/Yves` directory)
4. Clone the Docker-SDK (https://github.com/spryker/docker-sdk.git)
5. Run `docker/sdk bootstrap deploy.dev.yml`
6. Run `docker/sdk up -t`
7. Run `docker/sdk testing`

#### What is the expected result of these steps in the absence of the issue?
The file `docker/deployment/default/env/testing.env` is generated and `docker/sdk testing` succesfully opens a testing console.

#### What is the actual result?
An error is shown that `/home/spryker/cli/testing.env` does not exist, due to `docker/deployment/default/env/testing.env` not being generated:

```
/home/spryker/bin/cli.sh: line 15: /home/spryker/env/testing.env: No such file or directory
```

### What possible solutions and/or workarounds for the issue do you see?
- For each iteration of the group-loop (https://github.com/spryker/docker-sdk/blob/3608ed559d53d14df39e740c37b46b761633fefe/generator/index.php#L240), create a variable to hold all testing-related parameters
- Gather testing-related parameters in inner application-loop (https://github.com/spryker/docker-sdk/blob/3608ed559d53d14df39e740c37b46b761633fefe/generator/index.php#L241)
- Move `testing.env`-generation (https://github.com/spryker/docker-sdk/blob/3608ed559d53d14df39e740c37b46b761633fefe/generator/index.php#L362) to after completion of the per-group application-loop such that it does not depend on a specific application being present
- Make use of Twig-conditionals in `generator/src/templates/env/cli/testing.env.twig` to add specific application related environment variables only when related testing parameters have been gathered due to that application (e.g. Yves) being specified in the current group

**Comment by alexanderM91** [comment]
Hey @jabrandes, thanks a lot for your finding. 
If you have any issues fill comfortable to reopen the current issue.
