### ISSUE TITLE
docker/sdk export images fails with an exception when building spryker release 202108.0

### ISSUE THREAD

**Issue by mindcurv-vishnu** [spryker/docker-sdk#253]
### Which release, branch or hash of Docker SDK are you using?
Master

### Which operating system (platform/version/architecture) are you using?
Ubuntu x86_64

### What is the issue that you're experiencing?
docker/sdk export images fails with an exception (This command intended to be used non production environment only!)

#### What are the steps to reproduce the issue?
Clone the latest version of Spryker B2B (202108.0) and run below
1. docker/sdk bootstrap deploy.spryker-b2b-staging.yml
2. docker/sdk export images -t some-tag

#### What is the expected result of these steps in the absence of the issue?
Docker images are built

#### What is the actual result?
` 

 > [cli-production 6/6] RUN vendor/bin/install -r docker -s build-development:
#13 1.168 ================================================================================
#13 1.168 Install docker environment
#13 1.168 ================================================================================
#13 1.168
#13 1.168
#13 1.168  Section build-development
#13 1.168
#13 1.168
Command generate-transfers [vendor/bin/console transfer:generate] (5.68s)
Command generate-transfer-databuilders [vendor/bin/console transfer:databuilder:generate] (1.45s)
Command generate-auto-completion [vendor/bin/console dev:ide-auto-completion:generate] (2.06s)
#13 10.36 Command rest-api-generate-documentation [vendor/bin/console rest-api:generate:documentation] (In progress...)
#13 11.18 Store: DE | Environment: docker-staging
#13 11.18 Store: DE | Environment: docker-staging
#13 11.18 Store: DE | Environment: docker-staging
#13 11.18 Generated Yves IDE auto-completion files
#13 11.18 Generated Zed IDE auto-completion files
#13 11.18 Generated Client IDE auto-completion files
#13 11.18 Generated Service IDE auto-completion files
#13 11.18 Can not find dev:ide-auto-completion:glue:generate in your project.
#13 11.18 You can fix this by adding the missing command to your project ConsoleDependencyProvider.
#13 11.18 Store: DE | Environment: docker-staging
#13 11.18  This command intended to be used non production environment only!
#13 11.18
#13 11.18 In CommandLineExecutable.php line 107:
#13 11.18
#13 11.18   Aborted install...
#13 11.18
#13 11.18
#13 11.18 install [-r|--recipe RECIPE] [-d|--dry-run] [-s|--sections SECTIONS] [-g|--groups GROUPS] [-x|--exclude EXCLUDE] [-e|--include-excluded INCLUDE-EXCLUDED] [-i|--interactive] [-b|--breakpoint] [-a|--ask-before-continue] [-l|--log] [--] [<store>]
#13 11.18`

### What possible solutions and/or workarounds for the issue do you see?
Unsure

### Is there any other information that might be helpful?
Yes. The above steps works for spryker previous release 202009.0-p1

**Comment by alexanderM91** [comment]
Note: An issue isn't relevant for the latest Spryker release.
