### ISSUE TITLE
Adjust sdk to work with mutagen-compose instead of mutagen compose

### ISSUE THREAD

**Issue by maxim-tbx** [spryker/docker-sdk#272]
### Which release, branch or hash of Docker SDK are you using?
master

### Which operating system (platform/version/architecture) are you using?
macOS 11.6 Intel

### What is the issue that you're experiencing?
`Error: unknown command "compose" for "mutagen"`

#### What are the steps to reproduce the issue?
1. Update mutagen-beta to latest version
2. Run `docker/sdk up`

#### What is the expected result of these steps in the absence of the issue?
Spryker starts without issues

#### What is the actual result?
SDK crushes with this error

### What possible solutions and/or workarounds for the issue do you see?
Manual downgrade to version v0.13.0-beta2

### Is there any other information that might be helpful?
Mutagen Compose

Mutagen Compose is now the default and only supported Compose/Mutagen integration mechanism. It is a separate, self-contained Compose implementation (accessed via the mutagen-compose command) based on Compose V2.

The aging Compose V1 integration that shipped in the v0.12 and v0.13 beta releases is now removed, with v0.13.0-beta4 containing the most recent version.

https://github.com/mutagen-io/mutagen/releases/tag/v0.13.0

**Comment by maxim-tbx** [comment]
Process to downgrade:

1. Remove `mutagen` or `mutagen-beta`
2. Download version v0.13.0-beta2 from here: [intel](https://github.com/mutagen-io/mutagen/releases/download/v0.13.0-beta2/mutagen_darwin_amd64_v0.13.0-beta2.tar.gz) or [arm](https://github.com/mutagen-io/mutagen/releases/download/v0.13.0-beta2/mutagen_darwin_arm64_v0.13.0-beta2.tar.gz)
3. Extract archive and copy files `mutagen` and `mutagen-agents.tar.gz` to your `PATH`. In my case it was `/usr/local/bin/`

**Comment by alexanderM91** [comment]
Hi, the changes are available in https://github.com/spryker/docker-sdk/pull/263. 
Thank you.
