### ISSUE TITLE
"docker/sdk up" Problem with MariaDB and BackOffice

### ISSUE THREAD

**Issue by jcsepulvedar** [spryker/docker-sdk#275]
Hello,

Have been following the official documentation to install the SDK via Docker but every time I get the following errors:

"ERROR 1130 (HY000): Host '192.168.0.11' is not allowed to connect to this MariaDB server"

Also all end-points are reachable except for the BackOffice Endpoint, I just get a 502 from nginx.

Has anyone had this problem before? 
Thanks.

**Comment by alexanderM91** [comment]
Hi,
it seems to me that it was a local problem, as no one else encountered this problem.
