### ISSUE TITLE
Ability to disable the creation of service containers

### ISSUE THREAD

**Issue by philippzagar** [spryker/docker-sdk#303]
### What is the problem you are trying to solve by the feature?
As of now, the docker/sdk enables developers to state individual services together with possible engines in the `deploy.yml` file. However, if one of these services (in our case the `search` service, so ElasticSearch) isn't required at all, there's currently no possibility to just leave out a service completly in the deploy.yml` file, resulting in the creation of redundant service containers.

### What is the solution do you propose?
Adapt the generator so that it isn't required to state every possible service in the `deploy.yml` file. In the optimal case, one can just leave out a specific service (eg. the `search` service) and the docker/sdk is still able to generate a deployment without these services.

#### What changes in deploy.yml format do you propose?
As mentioned, in the optimal case the developer is able to leave out a specific service completly, assuming that the rest of the `deploy.yml` file also doesn't rely on the left out service (e.g. by specifying a namespace for a specific service, for example search, for a region of the store)

#### What changes in command line interface do you propose?
No need to.

### What alternatives have you considered?
Of course, one can adjust the generated `docker-compose.yml` file manually in order to avoid the startup of a specific service container. However, this is a very "hacky" solution and one has to repeat the procedure after every new deployment generation.

**Comment by philippzagar** [comment]
@alexanderM91 Thanks for the reply.
Is there any ETA you can give me regarding the implementation of this "feature" in the docker/sdk?

**Comment by philippzagar** [comment]
@alexanderM91 ping ;)

**Comment by alexanderM91** [comment]
Hey, 
I cannot provide you concrete ETA as the feature in our backlog and hasn't started yet but an approximate ETA, it's the end of the Q2.

Thank you.

**Comment by philippzagar** [comment]
@alexanderM91 What's the status of the issue? As Q2 comes to an end, it would be really great if the bug gets resolved soon :)

**Comment by alexanderM91** [comment]
Hi @philippzagar,
as I wrote previously the bug ticket in the queue and unfortunately we had to move it into Q3 due to other priorities.  

As soon as I have any precise information, I will provide an update.

**Comment by philippzagar** [comment]
@alexanderM91 Ping :)

**Comment by alexanderM91** [comment]
Hi @philippzagar,
Unfortunately, I don't have any updates about the current topic due to other priorities. 
I will try my best to speed up this process.
