### ISSUE TITLE
RUN /usr/bin/install -d -m 777 /var/run/opcache/debug - Permission denied

### ISSUE THREAD

**Issue by RobertSmolarczyk** [spryker/docker-sdk#312]
### Which release, branch or hash of Docker SDK are you using?

d72ae2fa0c73bf6428b19e5a8d36840693c2c35c (HEAD -> origin/master, tag: 1.42.1)

### Which operating system (platform/version/architecture) are you using?
macOs Monterey

### What is the issue that you're experiencing?

Running docker/sdk up:

RUN /usr/bin/install -d -m 777 /var/run/opcache/debug:
#6 0.187 /usr/bin/install: cannot create directory '/var/run/opcache': Permission denied

#### What are the steps to reproduce the issue?

Running docker/sdk up

#### What is the expected result of these steps in the absence of the issue?

local environment should run

**Comment by RobertSmolarczyk** [comment]
Output during this step when running up: 

`
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Building 0.6s (8/9)
 => [internal] load build definition from Dockerfile                                                                                                                                                                     0.0s
 => => transferring dockerfile: 244B                                                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                                                                                          0.0s
 => resolve image config for docker.io/docker/dockerfile:experimental                                                                                                                                                    0.2s
 => CACHED docker-image://docker.io/docker/dockerfile:experimental@sha256:600e5c62eedff338b3f7a0850beb7c05866e0ef27b2d2e8c02aa468e78496ff5                                                                               0.0s
 => [internal] load metadata for docker.io/library/spryker_b2b_dev_cli:dev                                                                                                                                               0.0s
 => CACHED [1/3] FROM docker.io/library/spryker_b2b_dev_cli:dev                                                                                                                                                          0.0s
 => [internal] load build context                                                                                                                                                                                        0.0s
 => => transferring context: 1.95kB                                                                                                                                                                                      0.0s
 => ERROR [2/3] RUN /usr/bin/install -d -m 777 /var/run/opcache/debug
`

**Comment by zhaklinab** [comment]
I have same issue.

**Comment by RobertSmolarczyk** [comment]
Just update the spryker sdk to the latest version(1.47.0).
Clear your docker image cache and try the install again. 

That worked on my machine.

**Comment by alexanderM91** [comment]
Hey @zhaklinab,
did you have a chance to check it out? 
Is it still reproducible?

**Comment by zhaklinab** [comment]
Works with the new version. Thank you!
