### ISSUE TITLE
[macos] error when running docker/sdk up: invalid characters for a local volume name

### ISSUE THREAD

**Issue by davidverholen** [spryker/docker-sdk#314]
### Which release, branch or hash of Docker SDK are you using?
latest master: 3966b3b4728e22fdf214d5830b18ad903593bfdb

### Which operating system (platform/version/architecture) are you using?
macOS version 11.6.5(20G527)
2 GHz Quad-Core Intel Core i5
mutagen 0.14.0

project root path is `/Users/firstname.lastname/git/project` , where firstname, lastname and project only contain a-z chars

### What is the issue that you're experiencing?
when running docker/sdk up, an error occurs:
`Error response from daemon: create ././docker/deployment/default/env/cli: "././docker/deployment/default/env/cli" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path`

#### What are the steps to reproduce the issue?
docker/sdk boot deploy.dev.yml && docker/sdk up --build

#### What is the expected result of these steps in the absence of the issue?
local env starts

#### What is the actual result?
error occurs and containers are not started

### What possible solutions and/or workarounds for the issue do you see?
none so far

**Comment by alexanderM91** [comment]
Hi @davidverholen,
can you please change the path  to the directory for the testing purpose with the usage of just a-zA-Z without any `.` character?

**Comment by davidverholen** [comment]
@alexanderM91 unfortunately this is not possible, since it's the username from our company domain which is set automatically. 

But the problem occurs on the macbook of a colleague, while on my machine (username: david.verholen) it works perfectly.

**Comment by alexanderM91** [comment]
In this case it seems OS specific problem and not DockerSDK.

**Comment by davidverholen** [comment]
@alexanderM91  is it possible to debug it somehow? Like where the docker sdk creates the volume name for the cli container?

**Comment by davidverholen** [comment]
@alexanderM91  that's my problem, on my machine everything works. But on my colleagues machine, same docker/sdk version, same project, same mutagen version, same docker for desktop configuration, also macOS 11.6, it breaks.

Would it be possible for us maybe to debug it on the machine, why the volume name is created wrong, or can you maybe point me to the part where it is set (I guess somewhere in the deployment/default code)?

**Comment by alexanderM91** [comment]
Hi @davidverholen, it looks like an issue in the docker-compose - https://github.com/docker/compose/issues/9428

**Comment by alexanderM91** [comment]
Good morning, @davidverholen

Can you please update an environment and recheck again with the latest docker/sdk version?
Thank you and have a great week.

**Comment by davidverholen** [comment]
@alexanderM91  thanks, yes it works now. (we have another issue now but it is related to an outdated npm package which is still required in the project I think)
