### ISSUE TITLE
[WSL2] Problem on docker/sdk up

### ISSUE THREAD

**Issue by IanCouto** [spryker/docker-sdk#316]
### Which release, branch or hash of Docker SDK are you using?

master

### Which operating system (platform/version/architecture) are you using?

Windows 11, with WSL2

### What is the issue that you're experiencing?

![image](https://user-images.githubusercontent.com/48738352/166983912-f08a1086-a596-4a69-aed9-bcdb00d17392.png)

#### What are the steps to reproduce the issue?

I create a new enviroment following the instructions on Spryker documentation and when I use the command to star the enviroment it happens

#### What is the expected result of these steps in the absence of the issue?

star the enviroment

#### What is the actual result?

the error I showed on the print

### What possible solutions and/or workarounds for the issue do you see?

change the source of the clone

**Comment by alexanderM91** [comment]
Hey @IanCouto,

the issue caused by the DMCA takedown of `codeitnowin/barcode-generator` repository.

We have several options how to solve it:

```Option 1: Use spryker/barcode-laminas as replacement for spryker/code-it-now
Step 1: Composer require the new module and update spryker/code-it-now

(optional, if module was used) composer remove spryker/code-it-now
composer require spryker/barcode-laminas:"^1.0.0"
composer require laminas/laminas-barcode:^2.8.0 
Step 2:  Replace CodeItNew in the BarcodeDependency Provider

In src/Pyz/Service/Barcode/BarcodeDependencyProvider.php replace use Spryker\Service\CodeItNow\Plugin\Code128BarcodeGeneratorPlugin; with use Spryker\Service\BarcodeLaminas\Plugin\Code128BarcodeGeneratorPlugin;

Option 2: Updating and continue using spryker/code-it-now
If you want to use this option you will need to update to the most recent version of the module by running the following:

composer update spryker/code-it-now
```

Have a great day.
