### ISSUE TITLE
Generator docker won't build

### ISSUE THREAD

**Issue by kfrohwein** [spryker/docker-sdk#32]
Running `docker/sdk bootstrap`

will always end in:
`++ docker build -t spryker_docker_sdk -f docker/generator/Dockerfile docker/generator
[+] Building 1.1s (4/4) FINISHED                                                
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 1.06kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 48B                                           0.0s
 => resolve image config for docker.io/docker/dockerfile:experimental      0.9s
 => CACHED docker-image://docker.io/docker/dockerfile:experimental@sha256  0.0s
failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: exit code: 1`

The reason is the usage of `# syntax = docker/dockerfile:experimental` because you want to use a cache mount. Sadly I don't know why it won't build locally. I have buildkit active in my docker daemon but it just won't work and I can't find any information on this issue on the net.

Docker version 19.03.2, build 6a30dfca03
Ubuntu 19.04

**Comment by marek-obuchowicz** [comment]
Does anything change if you use more specific builder tag? for example:
```
# syntax = docker/dockerfile:1.0.2-experimental
```

**Comment by marek-obuchowicz** [comment]
Please also have a look on #33 and make sure that `spryker-docker-sdk` is cloned into `docker` directory within the project directory, not next to it.

**Comment by kfrohwein** [comment]
This is what I did:

- git clone git@github.com:winterhalter-fenner/akona.git akona-docker
- cd akona-docker
- git clone git@github.com:spryker/docker-sdk.git docker
- composer install
- cd docker
- docker/sdk bootstrap

Result:

File "deploy.yml" is not accessible.
[+] Building 2.4s (4/4) FINISHED                                                                                                                  
 => [internal] load build definition from Dockerfile                                                                                         0.0s
 => => transferring dockerfile: 1.06kB                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                            0.0s
 => => transferring context: 48B                                                                                                             0.0s
 => resolve image config for docker.io/docker/dockerfile:experimental                                                                        2.3s
 => CACHED docker-image://docker.io/docker/dockerfile:experimental@sha256:888f21826273409b5ef5ff9ceb90c64a8f8ec7760da30d1ffbe6c3e2d323a7bd   0.0s
failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: exit code: 1

**Comment by kfrohwein** [comment]
Always the same error if I specify a different dockerfile version.

 => CACHED docker-image://docker.io/docker/dockerfile:1.0.2-experimental@sha256:cbd6491240cc8894d25e366ba83da19df1187f975dc3a5c2f88ce888ca6  0.0s
failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: exit code: 1

And it changes nothing if i put the SDK inside of a spryker root.

**Comment by kfrohwein** [comment]
I read some of the issues over at the buildkit repo. If I try to "make" buildkit i get the same error as running the spryker sdk. 

```➜  buildkit git:(master) make
hack/binaries
+ progressFlag=
+ '[' '' == true ']'
+ buildkitdTagsFlags=
+ '[' -n '' ']'
+ case $buildmode in
+ binariesDocker
+ mkdir -p bin/tmp
+ export DOCKER_BUILDKIT=1
+ DOCKER_BUILDKIT=1
++ mktemp -t docker-iidfile.XXXXXXXXXX
+ iidfile=/tmp/docker-iidfile.AMeCR2BgLd
++ echo ''
++ cut -d/ -f1
+ target=
+ '[' -z '' ']'
+ target=linux
+ docker build --build-arg BUILDKITD_TAGS= --target binaries-linux --iidfile /tmp/docker-iidfile.AMeCR2BgLd -f ./hack/dockerfiles/test.buildkit.Dockerfile --force-rm .
[+] Building 1.3s (4/4) FINISHED                                                                                                                  
 => [internal] load build definition from test.buildkit.Dockerfile                                                                           0.0s
 => => transferring dockerfile: 12.36kB                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                            0.0s
 => => transferring context: 49B                                                                                                             0.0s
 => resolve image config for docker.io/docker/dockerfile:1.1-experimental                                                                    1.1s
 => CACHED docker-image://docker.io/docker/dockerfile:1.1-experimental@sha256:888f21826273409b5ef5ff9ceb90c64a8f8ec7760da30d1ffbe6c3e2d323a  0.0s
failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: exit code: 1
make: *** [Makefile:4: binaries] Error 1
```

**Comment by marek-obuchowicz** [comment]
I can't reproduce the issue :| I think that as it also happens with non-spryker project, it might have something to do with your docker installation and/or configuration. I recommend opening an upstream issue in [moby/buildkit](https://github.com/moby/buildkit/issues)

**Comment by kfrohwein** [comment]
Thank you will do :)
