### ISSUE TITLE
Don't use "docker" as recommended folder name

### ISSUE THREAD

**Issue by kfrohwein** [spryker/docker-sdk#33]
I have a "Projects" folder with a lot of projects inside. And I clone your project into it. It's not that useful to have a folder called "docker" if I am looking for the "spryker-docker-sdk" or something like that :)

**Comment by marek-obuchowicz** [comment]
If you have folder "Projects" and there let's say: "Spryker1", then you should clone `spryker-docker-sdk` *inside* your project directory (`Projects/Spryker1/docker`), not next to your project directory (`Projects/docker`).

**Comment by kfrohwein** [comment]
Yes but the README.md suggest to clone into the folder 
`git clone https://github.com/spryker/docker-sdk.git ./docker`

Sorry if it was not clear what I was talking about. I would change the README.md in that regards.

**Comment by kfrohwein** [comment]
Sorry I just re-read #32  I didn't guess that you want me to clone into a spryker installation. In that case the folder name makes sense. I thought that I have to clone this project stand alone for any spryker project I am working on and just use the prepared docker templates.

**Comment by marek-obuchowicz** [comment]
@kfrohwein thanks for you feedback - we might need to review docs and make sure that it's stated in a more clear and precise way. @sprymiker can you please ask docs team to review this information?
