### ISSUE TITLE
Problems with Kibana

### ISSUE THREAD

**Issue by Yury-Klimashonak** [spryker/docker-sdk#331]
### Which release, branch or hash of Docker SDK are you using?
Release 1.48.1 Master branch

### Which operating system (platform/version/architecture) are you using?
MacOS Monterey 12.4 M1 Chip
Mutagen version 0.14.0
Compose version v2.5.0
Docker version v20.10.12

### What is the issue that you're experiencing?
I'm trying to start Kibana 7.6.

#### What are the steps to reproduce the issue?
I added to  **services** section in **deploy.dev.yml**

>
     kibana:
        engine: kibana
        version: 7.6
        endpoints:
            kibana.spryker.local:

#### What is the actual result?
When I open url kibana.spryker.local I see 

> 
    Kibana server is not ready yet

**Comment by Yury-Klimashonak** [comment]
[kibana.log](https://github.com/spryker/docker-sdk/files/8830883/kibana.log)

**Comment by Yury-Klimashonak** [comment]
Repo:
https://github.com/spryker-projects/b2b-mp-demo

**Comment by alexanderM91** [comment]
Hey, 
Kibana 7.6 doesn't support ARM arch - https://hub.docker.com/_/kibana?tab=tags&page=1&name=7.6.
Is it possible to switch from '7.6' to '7.10' for ES and Kibana services?

**Comment by alexanderM91** [comment]
https://github.com/spryker/docker-sdk/pull/332
