### ISSUE TITLE
Set SPRYKER_DEBUG_PROPEL_ENABLED depending if docker debug is set

### ISSUE THREAD

**Issue by dblaichinger** [spryker/docker-sdk#367]
### What is the problem you are trying to solve by the feature?

* In order to make use of `Propel::getConnection()->getLastExecutedQuery()` the Propel debug flag need to be set first.
* It would be great if this can be set similar to `SPRYKER_DEBUG_ENABLED` which depends on `project['docker']['debug']['enabled']`.

### What is the solution do you propose?

* https://github.com/spryker/docker-sdk/pull/368

### What alternatives have you considered?

* Locally modify config `$config[PropelConstants::PROPEL_DEBUG]` and set `true` instead of getting it from env variable, see [config_default-docker.dev.php]()https://github.com/spryker-shop/b2c-demo-shop/blob/master/config/Shared/config_default-docker.dev.php#L50)

**Comment by alexanderM91** [comment]
Close as issue as it's not part of the DockerSDK.
An issue will be solved at the project level via environment configuration adjustments.
