### ISSUE TITLE
Docker SDK sets wrong xDebug host ip environment variable when using WSL 2

### ISSUE THREAD

**Issue by jkreller** [spryker/docker-sdk#376]
### Which release, branch or hash of Docker SDK are you using?
master (e97f950)

### Which operating system (platform/version/architecture) are you using?
Windows and Docker on WSL2

### What is the issue that you're experiencing?
When trying to debug according to [the documentation](https://docs.spryker.com/docs/scos/dev/the-docker-sdk/202204.0/configuring-debugging-in-docker.html), the IDE won't get in any connection.

#### What are the steps to reproduce the issue?
Follow [the documentation](https://docs.spryker.com/docs/scos/dev/the-docker-sdk/202204.0/configuring-debugging-in-docker.html#configuring-phpstorm-for-xdebug) to setup xDebug with Windows using Docker on WSL2.

#### What is the expected result of these steps in the absence of the issue?
PHPStorm is getting in a request from xDebug and the step debugger works.

#### What is the actual result?
PHPStorm is not getting any connection and debugging is impossible.

### What possible solutions and/or workarounds for the issue do you see?
The reason is that Spryker sets the wrong `xdebug.client_host` (which is stored in `SPRYKER_XDEBUG_HOST_IP` environment variable). In my case it's setting `192.168.67.3` instead of `172.27.64.1`.
That's because within [docker.sh](https://github.com/spryker/docker-sdk/blob/master/bin/environment/docker.sh#L62-L77) it jumps into the 'linux' section and executes the wrong command. Correct would be the command within 'windows' section. This platform variable is set in [platform.sh](https://github.com/spryker/docker-sdk/blob/master/bin/platform.sh#L4-L5). WSL2 outputs "Linux" when executing `uname`.
Therefore another way has to be found to figure out if WSL2 is used.

Workaround (but just a quick fix) is to manually execute `tail -1 /etc/resolv.conf | cut -d' ' -f2` on WSL2 and replace `xdebug.client_host` in `docker/deployment/default/context/php/debug/etc/php/debug.conf.d/69-xdebug.ini` after bootstrapping.

**Comment by cboursinos** [comment]
Hello, we have the same issue in Windows with WSL2. We found also that the #341 is not fixing the issue, but also creates bug.

**Comment by alexanderM91** [comment]
Hi, 
the fix should be available in the latest master.

Our special gratitude to @fsmeier, @WinstonN :clap:
