### ISSUE TITLE
Missing SPRYKER_FE_HOST & SPRYKER_FE_PORT in glue-storefront

### ISSUE THREAD

**Issue by ynnoig** [spryker/docker-sdk#382]
### Which release, branch or hash of Docker SDK are you using?
Tag 1.49.6

### Which operating system (platform/version/architecture) are you using?
MacOS M1 Arm

### What is the issue that you're experiencing?
Missing SPRYKER_FE_HOST and SPRYKER_FE_PORT in glue-storefront application

#### What are the steps to reproduce the issue?
Call a glue-storefront-api and check the yves host/port value

#### What is the expected result of these steps in the absence of the issue?
We need in some api resource the Yves Host:Port to generate a deeplink to yves in json response

#### What is the actual result?
`not-configured-host` is just used as fallback value in config

### What possible solutions and/or workarounds for the issue do you see?
Add this code to this file `generator/src/templates/nginx/http/glue-storefront.server.conf.twig`
```
{% if project['_endpointMap'][endpointData['store']]['yves'] is not empty %}
    fastcgi_param SPRYKER_FE_HOST "{{ (project['_endpointMap'][endpointData['store']]['yves'] | split(':'))[0] | default('') }}";
    fastcgi_param SPRYKER_FE_PORT "{{ (project['_endpointMap'][endpointData['store']]['yves'] | split(':'))[1] | default(project['_defaultPort']) }}";
{% endif %}
```
### Is there any other information that might be helpful?
No.

**Comment by alexanderM91** [comment]
Hey @ynnoig,
agree, fully reasonable request\bug. We will put it in our backlog.

**Comment by alexanderM91** [comment]
Hi, the changes have been merged into the latest master.
