### ISSUE TITLE
docker/sdk reset command fails to run transfer:generate

### ISSUE THREAD

**Issue by weeg** [spryker/docker-sdk#383]
### Which release, branch or hash of Docker SDK are you using?
Unfortunately I don't know.

### Which operating system (platform/version/architecture) are you using?
macOS Monterey 12.6

### What is the issue that you're experiencing?
Running **docker/sdk reset** fails to generate transfer files.

#### What is the expected result of these steps in the absence of the issue?
The **src/Generated** files should be removed with the **docker/sdk reset** command, because old generated files can cause issues.

#### What is the actual result?
It fails when running **vendor/bin/console transfer:generate**

### What possible solutions and/or workarounds for the issue do you see?
Include **rm -rf vendor src/Generated** command for the **transfer:generate** or **docker/sdk reset** before running **vendor/bin/console transfer:generate**

**Comment by alexanderM91** [comment]
Hi @weeg, 
the fix is available in the latest master branch.
Thank you.
