### ISSUE TITLE
On Linux systems 'docker-compose' is not found when 'docker compose' is installed

### ISSUE THREAD

**Issue by ilstephano** [spryker/docker-sdk#385]
### Which release, branch or hash of Docker SDK are you using?
master

### Which operating system (platform/version/architecture) are you using?
Linux (Ubuntu 22.10, Debian 11)

**Docker:**
```
vagrant@99-bullseye:~/git/suite/docker$ docker version
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Docker Compose:**
```
vagrant@99-bullseye:~/git/suite/docker$ docker compose version
Docker Compose version v2.12.2
```

### What is the issue that you're experiencing?

I get 
```
vagrant@99-bullseye:~/git/suite$ docker/sdk boot deploy.yml 
'docker-compose' is not found. Please, make sure this application is installed and added to PATH. 
```
although docker compose v2 is installed 

#### What are the steps to reproduce the issue?
1. Move to a real linux cli, e.g. via
   1. Start a real linux node
   2. Install docker (e.g. "apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin")
2. Clone docker-sdk
3. run 'docker/sdk boot deploy.yml '

#### What is the expected result of these steps in the absence of the issue?

Docker sdk would run the commands 'boot' and 'run' without exiting because of missing 'docker-compose' binary.

#### What is the actual result?

```
vagrant@99-bullseye:~/git/suite$ docker/sdk boot deploy.yml 
'docker-compose' is not found. Please, make sure this application is installed and added to PATH. 
```
### What possible solutions and/or workarounds for the issue do you see?

A workaround is to symlink in the OS: `ln -s /usr/libexec/docker/cli-plugins/docker-compose /usr/local/bin/docker-compose`

Better would be to remove the required dependency to the binary  'docker-compose'  within the SDK

**Comment by alexanderM91** [comment]
Hi @ilstephano, 
an issue should be fixed in the latest master.

**Comment by ilstephano** [comment]
Thanx .. exactly the solution I expected :-)
