### ISSUE TITLE
Wrong NodeJS version with debian plattform image (image.node.version is ignored)

### ISSUE THREAD

**Issue by kj187** [spryker/docker-sdk#394]
### Which release, branch or hash of Docker SDK are you using?
1.49.7

### Which operating system (platform/version/architecture) are you using?
`ubuntu-18.04` on GitHub Actions

### What is the issue that you're experiencing?

Depending on the Plattform image I get a different issue with NodeJS.
Since the following SDK Update https://github.com/spryker/docker-sdk/commit/e9ebb666feccae1754792d41e49df3b9f95ef0aa it is possible to define the required Node and NPM version. 

Unfortunately this version will not be used! 
Instead, the Node version of the CLI image, which will be installed via "yarn" installation is used, which Node version is installed is depending on the plattform image. See

https://github.com/spryker/docker-sdk/blob/master/images/common/cli/Dockerfile#L35
https://github.com/spryker/docker-sdk/blob/master/images/common/cli/Dockerfile#L46

I have forked the Spryker Demo shop. See below.

#### What are the steps to reproduce the issue?

I forked the Spryker Demo shop. 
I updated `deploy.ci.acceptance.mariadb.yml` with the following
```yaml
image:
    node:
        version: 16
        distro: alpine
        npm: 8      
```

Next I updated the whole github workflow file, see https://github.com/elmerdigital/b2b-demo-shop/blob/master/.github/workflows/ci.yml 

To keep it simple, I removed all test excpet the MariaDB acceptance test. 
In each test case I just changed the SPRYKER_PLATFORM_IMAGE

To see which NodeJS version is installed I forked the Docker/SDK and added an `node --version` to `images/baked/assets/Dockerfile` line 20 https://github.com/elmerdigital/docker-sdk/commit/cabe55f0b3d5a6c9a8dae8657a352807f4993dac

The result is here: 
https://github.com/elmerdigital/b2b-demo-shop/actions/runs/3533792118/jobs/5929878947

Depending on the platform image I get instead of the defined and expected Node version 16

Alpine (correct versions)
- spryker/php:7.4 =  v16.18.0 (https://github.com/elmerdigital/b2b-demo-shop/actions/runs/3533792118/jobs/5929879380#step:5:11118)
- spryker/php:8.0-alpine3.16 = v16.18.0 (https://github.com/elmerdigital/b2b-demo-shop/actions/runs/3533792118/jobs/5929879198#step:5:11130)

Debian
- spryker/php:8.0-debian = v10.24.0 (https://github.com/elmerdigital/b2b-demo-shop/actions/runs/3533792118/jobs/5929878947#step:5:11371) 
![SCR-20221123-otc](https://user-images.githubusercontent.com/1647861/203603681-e2f01968-4db9-4cc2-9c73-19d7dab3f923.png)

- spryker/php:8.0-debian-buster = /usr/local/bin/node: No such file or directory (https://github.com/elmerdigital/b2b-demo-shop/actions/runs/3533792118/jobs/5929879577#step:5:10800)
![SCR-20221123-osi](https://user-images.githubusercontent.com/1647861/203603410-f5e1893d-440c-465f-9bb0-0e4f83b68ea8.png)

#### What is the expected result of these steps in the absence of the issue?

I would expect the Node version that I defined in my `deploy.ci.*.yaml` file

### What possible solutions and/or workarounds for the issue do you see?

I am not sure if `Yarn` and the implicit installed `nodejs` is still required in the CLI image 
https://github.com/spryker/docker-sdk/blob/master/images/common/cli/Dockerfile#L35
https://github.com/spryker/docker-sdk/blob/master/images/common/cli/Dockerfile#L46

As far as I know its required in the asset images, and for that there is already the new installation
https://github.com/spryker/docker-sdk/commit/e9ebb666feccae1754792d41e49df3b9f95ef0aa

So, maybe the solution is to remove the `Yarn` installation in the CLI image.

**Comment by kj187** [comment]
Update: I tried to remove `Yarn` installation from https://github.com/spryker/docker-sdk/blob/master/images/common/cli/Dockerfile

The result is, that node is now an unknown command. 
The copy of node does not work here https://github.com/spryker/docker-sdk/blob/master/images/common/application/Dockerfile.twig#L69

**Comment by kj187** [comment]
Related PR https://github.com/spryker/docker-sdk/pull/337
cc @zzyuzka

**Comment by alexanderM91** [comment]
Hi, 

Good catche but I could you please help me to clarify, why do we set `alpine` distro https://github.com/elmerdigital/b2b-demo-shop/blob/master/deploy.ci.acceptance.mariadb.yml#L12 for Debian image?
According to the CI logs we can see that the node version set properly but distro is incorrect. 
<img width="1083" alt="Screenshot 2022-11-24 at 10 01 26" src="https://user-images.githubusercontent.com/20976979/203739519-f76b7a43-e912-4def-84d4-e49d2a11e5d3.png">

Also, please note that [Debian Buster](https://endoflife.software/operating-systems/linux/debian) has been deprecated.


Some output from our CI which runs on the latest docker/sdk master branch without predefined distor.
<img width="749" alt="Screenshot 2022-11-24 at 10 08 53" src="https://user-images.githubusercontent.com/20976979/203742767-a3f57b4d-3153-4f11-848c-4f3b96522e33.png">

**Comment by kj187** [comment]
Ah damn.. thanks for that! 
The problem was the wrong NPM distro name AND the usage of debian buster. It works with bullseye now :-)
