### ISSUE TITLE
service "cli" is not running container

### ISSUE THREAD

**Issue by kj187** [spryker/docker-sdk#397]
### Which release, branch or hash of Docker SDK are you using?
master

### Which operating system (platform/version/architecture) are you using?
`ubuntu-18.04` on GitHub Actions

### What is the issue that you're experiencing?

The following error happens only **sporadically**, after a restart of the failed job it works without any issues.
In this case it was happen on Alpine, but it could also happen on Debian. Its totally sporadical.

https://github.com/elmerdigital/b2b-demo-shop/actions/runs/3540975943/jobs/5944669572
![SCR-20221124-kiw](https://user-images.githubusercontent.com/1647861/203799594-66bef97e-5bf6-43f4-968c-d5619b2c63f9.png)

#### What are the steps to reproduce the issue?

I forked the current Spryker Demo Shop (https://github.com/elmerdigital/b2b-demo-shop). 
The github CI which I use is the following (https://github.com/elmerdigital/b2b-demo-shop/blob/master/.github/workflows/ci.yml) 

```bash
git clone https://github.com/spryker/docker-sdk.git ./docker
docker/sdk boot -v deploy.ci.acceptance.mariadb.yml
docker/sdk up -t
docker/sdk testing console queue:worker:start --stop-when-empty
docker/sdk testing codecept run -c codeception.acceptance.yml
```

#### What is the expected result of these steps in the absence of the issue?

A successful Github job

**Comment by felixgeyer** [comment]
I'm not sure if it's really related but I'm currently experiencing the same issue with my local docker setup.

Apparently `node` is not installed properly.
Logs from my cli container: 
```/usr/local/bin/docker-php-entrypoint: line 9: /usr/local/bin/node: No such file or directory``` 

Starting the container without an entrypoint is possible (`docker run -it --entrypoint="" --user=root <id> /bin/bash`).
`node` is installed within the container at `/usr/bin/node` but not `/usr/local/bin/node`.

**Comment by kj187** [comment]
Its still an daily issue for us

Its the same issue with Postgress which is already solved https://github.com/spryker/docker-sdk/pull/381

Please just replace line 48 in https://github.com/spryker/docker-sdk/blob/master/bin/service/database/mysql.sh#L48
with ( [ ! -z "${tableCount}" ] &&  [ "${tableCount}" -gt 0 ]) && return "${TRUE}" || return "${FALSE}" to fix this issue

Thanks :)

**Comment by alexanderM91** [comment]
Hi, the fix should be available in the latest master.
Thank you.
