### ISSUE TITLE
bin/service/database/mysql.sh: line 48: [: : integer expression expected

### ISSUE THREAD

**Issue by kj187** [spryker/docker-sdk#417]
### What is the issue that you're experiencing?

```
No container found for cli_1
/spryker/docker/deployment/default/bin/service/database/mysql.sh: line 48: [: : integer expression expected
```

https://github.com/spryker/docker-sdk/blob/master/bin/service/database/mysql.sh#L48

Its the same issue with Postgress which is already solved https://github.com/spryker/docker-sdk/pull/381
Please replace line 48 in mysql.sh with `( [ ! -z "${tableCount}" ] &&  [ "${tableCount}" -gt 0 ]) && return "${TRUE}" || return "${FALSE}"` to fix this issue

**Comment by alexanderM91** [comment]
Hi, the issue is duplicated in https://github.com/spryker/docker-sdk/issues/397

**Comment by kj187** [comment]
Ahhhrr true ;) -> Closed
