### ISSUE TITLE
failed to get console during docker/sdk up

### ISSUE THREAD

**Issue by newLoki** [spryker/docker-sdk#457]
### Which release, branch or hash of Docker SDK are you using?

https://github.com/spryker/docker-sdk/releases/tag/1.59.0

### Which operating system (platform/version/architecture) are you using?

Linux/Ubuntu-22.04/x64 on Azure (see https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230728.3)

### What is the issue that you're experiencing?

Azure updated all container images for build in azure devops pipelines and suddenly `docker/sdk up` failed with 

```
Generating script.
Script contents:
docker/sdk up -t
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/08b6a3b9-5774-4652-ac58-0bbd6ee71e53.sh
Warning: Neither SSH agent or COMPOSER_AUTH is configured. Private repositories would not be accessible. 
-->  TESTING MODE   
ERROR: failed to get console: provided file is not a console
```

#### What are the steps to reproduce the issue?

Run `docker/sdk up` within the VM https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230728.3

#### What is the expected result of these steps in the absence of the issue?

`docker/sdk up` is running fine and builds the containers.

#### What is the actual result?

`ERROR: failed to get console: provided file is not a console` and no container is build.

### What possible solutions and/or workarounds for the issue do you see?

Workaround: put `PROGRESS_TYPE=plain` in front of `docker/sdk up`
Fix: the docker-sdk is detecting if a tty is available almost everywhere, but not for the progress bar, here it assumes that a tty is present (https://github.com/spryker/docker-sdk/blob/master/generator/src/templates/deploy.bash.twig#L105). 
Here it should use `Environment::getDockerComposeTTY` as well to check if a tty is available. 

### Is there any other information that might be helpful?

This issue might also appear on github actions, as they use the same base container from Microsoft azure. But it might also be the case that the container has a tty available in github actions.

**Comment by zyuzka** [comment]
@newLoki, thanks for your help. Issue fixed into https://github.com/spryker/docker-sdk/pull/458
