### ISSUE TITLE
Reduce verbosity of `composer install` in `application-production-dependencies` stage

### ISSUE THREAD

**Issue by elchenberg** [spryker/docker-sdk#481]
### What is the problem you are trying to solve by the feature?

Building images produces a lot of output. This might not be noticed in environments where the type of progress output of docker compose is `tty` but in our CI pipelines the output type is `plain`. The log output of the pipeline job that runs `docker/sdk export images` is about 1.4 MiB in our case and most of it is because this line:

<https://github.com/spryker/docker-sdk/blob/6f1a7372744d60d1736a2020c2074cba22cca547/images/baked/application/Dockerfile#L14>

### What is the solution do you propose?

Remove the `-vvv` from the line mentioned above.

#### What changes in deploy.yml format do you propose?

None.

#### What changes in command line interface do you propose?

None.

### What alternatives have you considered?

Setting the environment variable `PROGRESS_TYPE` to `quiet` instead of `plain` in our pipeline jobs. But having *some* output would be nice.

**Comment by alexanderM91** [comment]
Hi @elchenberg,

To address the current request, we plan to introduce a configuration option for the composer verbose mode.

For more details, please refer to the [PR](https://github.com/spryker/docker-sdk/pull/541/files#diff-48456f25a9965f118a75a3f431a2df9e212f6ad5ff35c4ee452692c02c74feb1R845).

Best regards,
Alex
