### ISSUE TITLE
down command returns error when bootstrapped with docker.dev.yml

### ISSUE THREAD

**Issue by fabianofa** [spryker/docker-sdk#51]
Once started, containers can't be removed by running `docker/sdk down`command when boostraped with default `deploy.dev.yml` file. Tested on Ubuntu 18.04, docker 19.03.4, docker-compose 1.14.1 4667896b

Steps to reproduce:

1. Follow all steps on Development Mode available at: https://documentation.spryker.com/installation/spryker_in_docker/getting-started-with-docker-201907.htm
2. Run: `$ docker/sdk down`

Result:

```
$ docker/sdk down
*** DEVELOPMENT MODE
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
```

Expected result:

    Remove all containers.

Notes:

A quick fix was made by adding `-r` to `stopCliContainer` function at docker/development/default script, and editing `genetor/src/templates/deploy.bash.twig`. Problem is, the `-r` is not compatible with MacOS. May I make a pull request on this fix?

> 
>        -r, --no-run-if-empty
>               If the standard input does not contain any nonblanks, do not
>               run the command.  Normally, the command is run once even if
>               there is no input.  This option is a GNU extension.

source: http://man7.org/linux/man-pages/man1/xargs.1.html

**Comment by tvaleriy** [comment]
Hi Fabiano,

thank you for reporting this issue. This one is known already but corresponding code will be reworked as part of another issue so is not relevant kind of. So I'm closing this ticket and related PR.

Best,
Spryker Support Team
