### ISSUE TITLE
NPM install hangs for dashboard on W10 and W11 with latest node:alpine

### ISSUE THREAD

**Issue by SimoSavonenVincit** [spryker/docker-sdk#520]
### Which release, branch or hash of Docker SDK are you using?
1.62.0 master

### Which operating system (platform/version/architecture) are you using?
W10 (Ubuntu 22.04.5 LTS in WSL2) and W11

### What is the issue that you're experiencing?
`docker/sdk up` doesn't finish, it hangs during the dashboard setup, while running command `npm install log.io pm2 -g`

#### What are the steps to reproduce the issue?
I was able to reproduce this with a fresh W11 install, where I started from nothing and installed the latest [b2c demoshop](https://github.com/spryker-shop/b2c-demo-shop/releases/tag/202404.0).
This issue also appeared on a W10 machine by itself, projects that started fine on monday, stopped working on 17.10.2024.

#### What is the expected result of these steps in the absence of the issue?
docker/sdk up would work

#### What is the actual result?
docker/sdk up hangs

### What possible solutions and/or workarounds for the issue do you see?
Editing the file _docker/deployment/default/images/common/dashboard/Dockerfile_, replacing `node:alpine` with `node:18-alpine`

**Comment by SimoSavonenVincit** [comment]
<img width="675" alt="npm install hangs Windows10" src="https://github.com/user-attachments/assets/e24520fa-fb54-4e1f-8832-d957968b41d5">

**Comment by alexanderM91** [comment]
Hi @SimoSavonenVincit, 
Your assumption was correct. The fix is now available in the latest version of the master branch.

**Comment by MatheusOliveira10** [comment]
Hi! I am facing the same problem. And it was not solved by the node:22-alpine3.20 image. Using node:18-alpine solved it :)
