### ISSUE TITLE
Endpoint ports and default port 80 usage

### ISSUE THREAD

**Issue by kfrohwein** [spryker/docker-sdk#60]
https://github.com/spryker/docker-sdk/blob/ec491a7e9123ce7fee3d87ae7cfa992556c455d1/generator/index.php#L218

This will always bind the frondend container to port 80 which is not desirable. If I remove the default setting from the array everything goes as I desire. So I suggest to remove that entry to the array.

And it feels real strange to add all endpoints like "endpoint:80". In this case I mean the usage of double quotes around the yml keys. I would suggest to change this to a standard yml setting just below the endpoint name like

endpoint:
    port: 8080

**Comment by tvaleriy** [comment]
Hi Karsten,
thank you for reporting this. This is known already and should be fixed relatively soon.
I want to ask you to report such an issues (not related to documentation but everything else) here - https://support.spryker.com/hc/en-us/requests/new. Thanks!

I will notify here when it's fixed.

Best,
Spryker Support Team

**Comment by kfrohwein** [comment]
Sorry but I won't report any issues in that mess of a form. If I want to support you in a community manner then do it in a community manner. I will only post there if it is directly work related and do this as your licence paying industry partner...

**Comment by tvaleriy** [comment]
Hi @kfrohwein,

this should have been fixed here - https://github.com/spryker/docker-sdk/releases/tag/1.6.1.
But also there is newer version already.

Best,
Spryker Support Team
