### ISSUE TITLE
 ERROR resolve image config for docker.io/docker/dockerfile:experimental on widnows

### ISSUE THREAD

**Issue by SchmidtDawid** [spryker/docker-sdk#95]
On Linux system everything is working fine, but on windows and WSL i got error during docker/sdk boot:

```
dawid@DESKTOP-IK089RK:/c/Users/schmi/dev/spryker$ docker/sdk boot

[+] Building 0.2s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                                         0.0s  => => transferring dockerfile: 38B                                                                                                          0.0s  => [internal] load .dockerignore                                                                                                            0.0s  => => transferring context: 34B                                                                                                             0.0s  => ERROR resolve image config for docker.io/docker/dockerfile:experimental                                                                  0.2s ------
 > resolve image config for docker.io/docker/dockerfile:experimental:
------
failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: `Error spawning command line “dbus-launch --autolaunch= --binary-syntax --close-stderr”: Child process exited with code 1`
dawid@DESKTOP-IK089RK:/c/Users/schmi/dev/spryker$
dawid@DESKTOP-IK089RK:/c/Users/schmi/dev/spryker$ docker/sdk boot
[+] Building 0.2s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                                         0.0s  => => transferring dockerfile: 38B                                                                                                          0.0s  => [internal] load .dockerignore                                                                                                            0.0s  => => transferring context: 34B                                                                                                             0.0s  => ERROR resolve image config for docker.io/docker/dockerfile:experimental                                                                  0.2s ------
 > resolve image config for docker.io/docker/dockerfile:experimental:
------
failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: `Error spawning command line “dbus-launch --autolaunch= --binary-syntax --close-stderr”: Child process exited with code 1`
```

I made everything like in this documentation: https://documentation.spryker.com/docs/docker-installation-prerequisites-windows

My deamon.json look like that:
```
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": true,
  "experimental": true,
  "features": {
    "buildkit": true
  }
}
```

**Comment by tvaleriy** [comment]
Hi @SchmidtDawid,
googling the error message regarding dbus gives this as possible solution - https://github.com/Microsoft/WSL/issues/2016#issuecomment-435091497. Could you please check it?

Best,
Spryker Support Team

**Comment by SchmidtDawid** [comment]
It doesn't help. I solve the problem but I don't really know how. I upgrade windows to fast ring, upgrade WSL to v2, reinstall all libs, downgrade to v1 and it works.
but i have another problem:

shutdown  Background docker-sync has been stopped
chmod: cannot access '/data/config/Zed/*.key': No such file or directory

Do i have to install zed sdk?

**Comment by tvaleriy** [comment]
There is nothing like zed sdk. If you cloned one of our demo-shops correctly, then these keys just should be there.

So far I can say that as per our product team the WSL2 support is coming soon and it might be a solution to all Windows+docker+docker sync related problems.

From my experience the only guaranteed option for Windows is using Vagrant devvm.

Best,
Spryker Support Team

**Comment by SchmidtDawid** [comment]
Ok, thanks for help. Its not demo project, but prepared by another team almost production ready. I'm going to ask them for help ;). 
On linux everything works fine anyway. I have to but Apple computer i think ;P

**Comment by dannysauer** [comment]
FWIW (for the people who search in the future), I had a similar issue happen in WSL2 and Docker Windows when docker was previously logged in to dockerhub and then had logged out.  Logging back in to a dockerhub account with Docker resolved the error.

**Comment by sgClaudia98** [comment]
I am having a similar error

![imagen](https://user-images.githubusercontent.com/63687204/194724189-cdafdc18-555b-4253-9306-9da301dd355e.png)

Any ideas, do I need to configure something for credentials inside DockerFile or devcontainer.json?
